version: '2'
services:
  octoprint:
    build: .
    image: arm32v7/octoprint
    container_name: arm32v7-octoprint
    ports:
      - 5000:5000
    # devices:
    #  - /dev/ttyACM0:/dev/ttyACM0
    volumes:
     - ./config:/home/octoprint/.octoprint
